### ISSUE TITLE
Component not starting without the outside temperature data

### ISSUE THREAD

**Issue by sytchi** [MizterB/homeassistant-infinitude#7] opened 2019-03-21 22:31 UTC
Since whether underground does not provide free api keys anymore I did not configure any in my infinitude instance.
https://www.wunderground.com/weather/api/

Unfortunately this leads to the component crashing during the load fase as it expects a value and gets an empty array in place of outside temperature

**Comment by bdf0506** [comment] 2019-03-22 14:42
I believe this should be a bug of infinitude itself, and not of the HA component which relies on infinitude. 

Secondly WUnderground is not actually required. I have mine running without a WUnderground key. So this may be a symptom of another issues and not actually a cause for alarm if you are seeing this.

**Comment by sytchi** [comment] 2019-03-22 21:57
It maybe is the infinitude problem (I can see NaN in infinitude). Anyway it's causing a crash of the whole component. Maybe it could fail gracefully and just ommit that if it's not present. There could be a warning in the logfile.
I can try to prepare a MR for that.

**Comment by MizterB** [comment] 2019-04-08 16:10
Can you please confirm if this is still a problem in the latest release?

**Comment by statuskwolek** [comment] 2019-04-13 20:00
*appears* it may still be at least for me.  Just pulled down the latest code and fresh install of Home Assistant.  Infinitude reflects NaN in the Web gui and checking the home assistant log I see...

`2019-04-13 15:52:14 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform infinitude
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 73, in setup_platform
    devices.append(InfinitudeZone(infinitude, zones[i]["id"], zoneName))
  File "/config/custom_components/infinitude/climate.py", line 116, in __init__
    self.update()
  File "/config/custom_components/infinitude/climate.py", line 140, in update
    self._outdoorTemperature = float(getSafe(self._systemStatus, "oat"))
TypeError: float() argument must be a string or a number, not 'dict'
`
Just basing the assessment on the fact that the trace seems to end at outdoor temperature...

**Comment by MizterB** [comment] 2019-05-31 18:55
I just pushed a potential fix for this.  However, in my system I kept getting an outside temperature reading without providing a Wunderground key (maybe this is coming from Carrier due to passthru?). Anyway, I could not fully test myself.  Could you validate?  Please grab the latest commit - I have not updated the release version yet.

**Comment by statuskwolek** [comment] 2019-06-01 02:02
Confirmed at least from my end that I now have a climate element that comprises of my single zone that reads the temperature and seems to allow me to monitor/control house temperature and away mode.

This pleases me greatly :)

**Comment by statuskwolek** [comment] 2019-06-01 02:11
I am definitely interested in understanding how you're getting weather data without a Wunderground key too btw :)

**Closed as completed** 2019-06-10 14:55 UTC
